// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6kp4IADwYeBzwjGyaf9qjKnO5PnN4uQ',
    appId: '1:856473879388:web:c8de19a67f04ef7f517799',
    messagingSenderId: '856473879388',
    projectId: 'mecounting',
    authDomain: 'mecounting.firebaseapp.com',
    storageBucket: 'mecounting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlqwMk9qKZXicflGwvpZFiQKMDzSD0-5A',
    appId: '1:856473879388:android:1bb3949683bd8676517799',
    messagingSenderId: '856473879388',
    projectId: 'mecounting',
    storageBucket: 'mecounting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCYWE9-bTHkGuuPNckWOK8Kkhq8VbBBek',
    appId: '1:856473879388:ios:62e5851422f1171e517799',
    messagingSenderId: '856473879388',
    projectId: 'mecounting',
    storageBucket: 'mecounting.appspot.com',
    iosClientId: '856473879388-aptdj5u1vnl466h88a3ht7m59o1o4us4.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountApp',
  );
}
